/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSanteIndexRouteImport } from './routes/_app.sante.index'
import { Route as AppProfilIndexRouteImport } from './routes/_app.profil.index'
import { Route as AppSanteModuleRouteImport } from './routes/_app.sante.$module'
import { Route as AppProfilSectionRouteImport } from './routes/_app.profil.$section'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSanteIndexRoute = AppSanteIndexRouteImport.update({
  id: '/sante/',
  path: '/sante/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIndexRoute = AppProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => AppRoute,
} as any)
const AppSanteModuleRoute = AppSanteModuleRouteImport.update({
  id: '/sante/$module',
  path: '/sante/$module',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilSectionRoute = AppProfilSectionRouteImport.update({
  id: '/profil/$section',
  path: '/profil/$section',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profil/$section': typeof AppProfilSectionRoute
  '/sante/$module': typeof AppSanteModuleRoute
  '/profil/': typeof AppProfilIndexRoute
  '/sante/': typeof AppSanteIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/': typeof AppIndexRoute
  '/profil/$section': typeof AppProfilSectionRoute
  '/sante/$module': typeof AppSanteModuleRoute
  '/profil': typeof AppProfilIndexRoute
  '/sante': typeof AppSanteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/profil/$section': typeof AppProfilSectionRoute
  '/_app/sante/$module': typeof AppSanteModuleRoute
  '/_app/profil/': typeof AppProfilIndexRoute
  '/_app/sante/': typeof AppSanteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/profil/$section'
    | '/sante/$module'
    | '/profil/'
    | '/sante/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/'
    | '/profil/$section'
    | '/sante/$module'
    | '/profil'
    | '/sante'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/'
    | '/_app/profil/$section'
    | '/_app/sante/$module'
    | '/_app/profil/'
    | '/_app/sante/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sante/': {
      id: '/_app/sante/'
      path: '/sante'
      fullPath: '/sante/'
      preLoaderRoute: typeof AppSanteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/': {
      id: '/_app/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof AppProfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sante/$module': {
      id: '/_app/sante/$module'
      path: '/sante/$module'
      fullPath: '/sante/$module'
      preLoaderRoute: typeof AppSanteModuleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/$section': {
      id: '/_app/profil/$section'
      path: '/profil/$section'
      fullPath: '/profil/$section'
      preLoaderRoute: typeof AppProfilSectionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProfilSectionRoute: typeof AppProfilSectionRoute
  AppSanteModuleRoute: typeof AppSanteModuleRoute
  AppProfilIndexRoute: typeof AppProfilIndexRoute
  AppSanteIndexRoute: typeof AppSanteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProfilSectionRoute: AppProfilSectionRoute,
  AppSanteModuleRoute: AppSanteModuleRoute,
  AppProfilIndexRoute: AppProfilIndexRoute,
  AppSanteIndexRoute: AppSanteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
